services:
  redis:
    image: redis:7-alpine
    container_name: insider_alerts_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: insider_alerts_app
    depends_on:
      - redis
    environment:
      MONITORS: "SEC"
      REDIS_URL: "redis://redis:6379/"
    restart: unless-stopped

volumes:
  redis_data:
